---
- name: Create caddy configs directory
  file:
    path: /etc/caddy
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create caddy directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  loop:
    - /opt/caddy
    - /opt/caddy/bin

- name: Create caddy state directory
  file:
    path: /opt/caddy/.caddy
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Download caddy binary
  get_url:
    url: https://s3-us-west-2.amazonaws.com/shift-release-repo/caddy/0.11.4/caddy
    dest: /opt/caddy/bin/caddy
    owner: root
    group: root
    mode: 0755

- name: Deploy caddy config file
  template:
    src: "{{ jupyterhub_caddy_config_template }}"
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: 0640
  notify: restart caddy

- name: Create caddy systemd service
  template:
    src: caddy.service.j2
    dest: "{{ systemd_service_dir }}/caddy.service"
    owner: root
    group: root
    mode: 0755

- name: Enable caddy systemd service
  systemd:
    name: caddy
    enabled: yes
    daemon-reload: yes
    state: started
