---
- name: Deploy jupyterhub config file
  template:
    src: jupyterhub-config.py.j2
    dest: /etc/jupyterhub/jupyterhub_config.py
    owner: "{{ jupyterhub_user }}"
    group: "{{ jupyterhub_group }}"
    mode: 0600
  notify: Restart jupyterhub

- name: Check cookie secret exists
  stat:
    path: "{{ jupyterhub_cookie_secret_file }}"
  register: check_cookie_secret

- name: Generate cookie secret
  shell: 'openssl rand -hex 32 > "{{ jupyterhub_cookie_secret_file }}"'
  args:
    creates: "{{ jupyterhub_ssl_cert_file }}"
  notify:
    - Restart jupyterhub
    - Update cookie secret file

- name: Update cookie secret file
  file:
    path: "{{ jupyterhub_cookie_secret_file }}"
    owner: "{{ jupyterhub_user }}"
    group: "{{ jupyterhub_group }}"
    mode: 0600

- name: Check key file exists
  stat:
    path: "{{ jupyterhub_ssl_key_file }}"
  register: check_key

- name: Check certificate file exists
  stat:
    path: "{{ jupyterhub_ssl_cert_file }}"
  register: check_cert

- name: Create self-signed SSL cert
  shell: 'openssl req -new -nodes -x509 -rand /dev/urandom -config ${CONFIG} -subj "/C=${country}/ST=${state}/L=${city}/O=${org}/OU=${unit}/CN=${fqdn}/emailAddress=${email}" -sha${hash} -days ${expire} -keyout {{ jupyterhub_ssl_key_file }} -out {{ jupyterhub_ssl_cert_file }}'
  args:
    creates: "{{ jupyterhub_ssl_cert_file }}"
  when:
    - jupyterhub_ssl == True
    - check_key.stat.exists == False
    - check_cert.stat.exists == False
    - jupyterhub_ssl_key == ""
    - jupyterhub_ssl_cert == ""

- name: Deploy SSL key
  copy:
    src: "{{ jupyterhub_ssl_key }}"
    dest: "{{ jupyterhub_ssl_key_file }}"
    owner: "{{ jupyterhub_user }}"
    group: "{{ jupyterhub_group }}"
    mode: 0600
  when:
    - jupyterhub_ssl_key != ""
    - jupyterhub_ssl == True
  notify: Restart jupyterhub

- name: Deploy SSL cert
  copy:
    src: "{{ jupyterhub_ssl_cert }}"
    dest: "{{ jupyterhub_ssl_cert_file }}"
    owner: "{{ jupyterhub_user }}"
    group: "{{ jupyterhub_group }}"
    mode: 0600
  when:
    - jupyterhub_ssl_cert != ""
    - jupyterhub_ssl == True
  notify: Restart jupyterhub
