---
- name: Deploy jupyterhub config file
  template:
    src: jupyterhub-config.py.j2
    dest: /etc/jupyterhub/jupyterhub_config.py
    owner: "{{ jupyterhub_user }}"
    group: "{{ jupyterhub_group }}"
    mode: 0600
  notify: restart jupyterhub

- name: Check cookie secret exists
  stat:
    path: "{{ jupyterhub_cookie_secret_file }}"
  register: check_cookie_secret

- name: Generate cookie secret
  shell: 'openssl rand -hex 32 > "{{ jupyterhub_cookie_secret_file }}"'
  args:
    creates: "{{ jupyterhub_ssl_cert_file }}"
  notify: restart jupyterhub

- name: Write cookie secret file
  file:
    dest: "{{ jupyterhub_cookie_secret_file }}"
    owner: "{{ jupyterhub_user }}"
    group: "{{ jupyterhub_group }}"
    mode: 0600
  when: check_cookie_secret.stat.exists

- name: Check key file exists
  stat:
    path: "{{ jupyterhub_ssl_key_file }}"
  register: check_key

- name: Check certificate file exists
  stat:
    path: "{{ jupyterhub_ssl_cert_file }}"
  register: check_cert

- name: Create self-signed SSL cert
  command: 'openssl req -new -nodes -x509 -rand /dev/urandom -subj "/C={{ jupyterhub_ssl_country }}/ST={{ jupyterhub_ssl_state }}/L={{ jupyterhub_ssl_city }}/O={{ jupyterhub_ssl_org }}/OU={{ jupyterhub_org_unit }}CN={{ jupyterhub_fqdn }}" -days 3650 -keyout {{ jupyterhub_ssl_key_file }} -out {{ jupyterhub_ssl_cert_file }} -extensions v3_ca'
  args:
    creates: "{{ jupyterhub_ssl_cert_file }}"
  when:
    - jupyterhub_ssl == True
    - check_key.stat.exists == False
    - check_cert.stat.exists == False
    - jupyterhub_ssl_key == ''
    - jupyterhub_ssl_cert == ''

- name: Deploy SSL key
  copy:
    src: "{{ jupyterhub_ssl_key }}"
    dest: "{{ jupyterhub_ssl_key_file }}"
    owner: "{{ jupyterhub_user }}"
    group: "{{ jupyterhub_group }}"
    mode: 0600
  when: jupyterhub_ssl_key != ''
  notify: restart jupyterhub

- name: Deploy SSL cert
  copy:
    src: "{{ jupyterhub_ssl_cert }}"
    dest: "{{ jupyterhub_ssl_cert_file }}"
    owner: "{{ jupyterhub_user }}"
    group: "{{ jupyterhub_group }}"
    mode: 0600
  when: jupyterhub_ssl_cert != ''
  notify: restart jupyterhub
